lang: tr-TR
title: Rustgele
email: dengere@gmail.com
description: >- 
  Kurslarımı, başlangıç seviyesinden uzmanlık düzeyine kadar adım adım ilerleyecek şekilde yapılandırmak için özen gösterdim. 
  Kursların seviyelere göre doğru adımlarla sıralanmasını ve her seviyedeki kursun konu akışını, bir yazılım geliştirici ve eğitmen olarak deneyimlerimle harmanlayarak hazırladım.
baseurl:  /rustacean
url: dengere.github.io


# twitter_username: jekyllrb
# github_username:  dengere
linkedin_username:  nuriyilmaztech
# Build settings
theme: minima
plugins:
  - jekyll-feed