# Welcome to Jekyll!
#
# git commit -m "committing my jekyll theme"
# git add --all
# git push
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: rust_yolu
email: dengere@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Kurslarımı, başlangıç seviyesinden uzmanlık düzeyine kadar adım adım ilerleyecek şekilde yapılandırmak için özen gösterdim. 
  Kursların seviyelere göre doğru adımlarla sıralanmasını ve her seviyedeki kursun konu akışını, bir yazılım geliştirici ve eğitmen olarak deneyimlerimle harmanlayarak hazırladım.
  
  Site hakkında soru ve önerileriniz varsa, GitHub depomda bir issue açarsanız memnun olurum. Kurslar hakkında bilgi almak için e-posta adresimi kullanmanızı rica ederim.
baseurl: /rustacean # the subpath of your site, e.g. /blog
# description: >- # this means to ignore newlines until "baseurl:"
# baseurl: /rustacean # the subpath of your site, e.g. /blog
# # description: Kurslarımı, başlangıç seviyesinden uzmanlık düzeyine kadar adım adım ilerleyecek şekilde yapılandırmak için özen gösterdim. Kursların seviyelere göre doğru adımlarla sıralanmasını ve her seviyedeki kursun konu akışını, bir yazılım geliştirici ve eğitmen olarak deneyimlerimle harmanlayarak hazırladım. Umarım doğru yolu doğru bir şekilde sunabilmişimdir.
# # baseurl: /rustacean
url: dengere.github.io
# twitter_username: jekyllrb
github_username:  dengere
linkedin_username:  nuriyilmaztech
show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/